#!/usr/bin/env bash

# PhpStorm URL Handler
# phpstorm://open?url=file://@file&line=@line
# phpstorm://open?file=@file&line=@line
#
# @license GPL
# @author Stefan Auditor <stefan.auditor@erdfisch.de>

arg=${1}
urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }
arg=$(urldecode "${arg}")
pattern=".*file(:\/\/|\=)(.*)&line=(.*)"

# Get the file path.
file=$(echo "${arg}" | sed -r "s/${pattern}/\2/")

# Get the line number.
line=$(echo "${arg}" | sed -r "s/${pattern}/\3/")

/usr/bin/env ~/.local/share/JetBrains/Toolbox/apps/PhpStorm/ch-0/202.7660.42/bin/phpstorm.sh --line "${line}" "${file}"

